### ISSUE TITLE
Please consider adding license

### ISSUE THREAD

**Issue by huedev** [rylydou/awakening#1]
Hi @rylydou, this is a really cool project! There's several simple Godot tutorials and sample projects out there that just barely scratch the surface of what's possible, but it's rare to see a project that feels pretty feature complete.

Would you consider adding a license so that users (such as myself!) have a better idea of your intentions of having this project's repository available and know whether it's okay to take a closer look at its inner workings?

If you're not comfortable with that, no worries!

**Comment by rylydou** [comment]
This project was a Links Awakening fan game I was working on last year, but I never got around to finishing it. I later made this repository public when applying for jobs to actually build a portfolio. I think that I am going to abandon this project so I might as well give it a license. I'm licensing it under `CC-BY-NC` (attribution required, commercial use not allowed) for now. I hope this license is permissive enough to allow people to look at the code while preventing blatant "asset flips" or other things of the sort.

I think the project being an educational tool would be great and including it in the Godot Asset Library would be perfect but since the game uses a lot of ripped textures from Link's Awakening I'm not sure if the project will be accepted.

If you have any questions about the code or anything else feel free ask me on discord: `@ciberturtle`

**Comment by huedev** [comment]
This is great, I think that seems like a good license for allowing your work to be an educational resource while respecting the time and effort you put into it.

I was also kind of curious how the ripped textures would play into this sort of thing, I think you're right that would probably be an issue from Godot's point of view, but it's hard to say for sure.

I'll mark the issue as closed. Thanks for taking the time to add a license, and thanks for the offer, I'll reach out if I have any questions for you!
